### ISSUE TITLE
How to make horizontal scrollbar visible on top of the div instead of the bottom?

### ISSUE THREAD

**Issue by ayruskrish** [noraesae/perfect-scrollbar#290]

**Comment by noraesae** [comment]
Hi,

Please add following lines to your css.

```css
.ps-container .ps-scrollbar-x-rail {
  top: 3px;
  bottom: auto; /* If using `top`, there shouldn't be a `bottom`. */
}
```

You can also find an example for the case in `examples/scrollbars-on-the-opposite-side.htm`.

Cheers,
