### ISSUE TITLE
Feature request: add options to hide one/both scrollbars but still allow scrolling (no supress)

### ISSUE THREAD

**Issue by ifrim** [noraesae/perfect-scrollbar#322]
Feature request: add options to hide one/both scrollbars but still allow scrolling (no supress)

**Comment by noraesae** [comment]
You can do this with just CSS. Please add following lines in any of your CSS files.

```css
.ps-container > .ps-scrollbar-x-rail {
  visibility: hidden;
}
.ps-container > .ps-scrollbar-y-rail {
  visibility: hidden;
}
```

You can surely choose which scrollbar to hide by adding only one of them.

Thanks!
