### ISSUE TITLE
Need scrollXStartingOffset and scrollYStartingOffset

### ISSUE THREAD

**Issue by totszwai** [noraesae/perfect-scrollbar#323]
I don't think there is currently a way to initialize the scrollbar to start at xx amount of pixel? When initializing the bar, it always sets right: 3px;

However the user may not want to start at just 3px. Is there currently a workaround for this? I'd hate to use: .ps-scrollbar-y-rail { right: 10px !important; }

**Comment by noraesae** [comment]
Without the ugly `!important`, you can do like this:

```css
.ps-container > .ps-scrollbar-y-rail {
  right: 10px;
}
```

Would it look a bit better to you?
