### ISSUE TITLE
perfectScrollbar not working over disabled <inputs>

### ISSUE THREAD

**Issue by VPenkov** [noraesae/perfect-scrollbar#385]
Firefox only:
If I have an <input type="text" disabled> and attempt to scroll while my mouse is over it, nothing happens.

**Comment by VPenkov** [comment]
Seems like a Firefox issue. The same bug occurs in virtually all custom scrollbar plugins. Any idea why?

**Comment by zomp** [comment]
Isn't it caused by `-moz-user-input: disabled;` applied on (by default) `input:disabled, textarea:disabled, option:disabled, optgroup:disabled, select:disabled:disabled`?

**Comment by VPenkov** [comment]
You seem to be correct.
Is there something I should know about this? Any workaround maybe?

**Comment by zomp** [comment]
You can simply modify your CSS (or more specifically):
```css
.ps-container input:disabled,
.ps-container textarea:disabled,
.ps-container option:disabled,
.ps-container optgroup:disabled,
.ps-container select:disabled:disabled {
  -moz-user-input: inherit;
}
```

**Comment by VPenkov** [comment]
Yeah, unfortunately it's not the same in a few ways:
1) Disabled inputs don't actually get submtited with the form (readonly do)
2) You can actually interact with a field with which you're not supposed to. That's bad UX.
3) This doesn't work too nicely, unfortunately.

I resolved my issue by adding a transparent div on top of my disabled inputs and scanning for it when necessary (more on that later).
I did find a few scrollbars that don't have the issue but unfortunately I'm not too savvy with javascript to commit anything more useful than opening an issue and giving some info.
This one works: https://github.com/jnicol/trackpad-scroll-emulator
This one also works: https://github.com/noeldelgado/gemini-scrollbar
There was one more but I lost it somewhere.

Not sure what they do differently but I'm hoping to give an idea or two.

As a workaround I did the following:
1) I put all my inputs inside <div class="field">
2) I wrote this: 
```html
var is_firefox = /Firefox/i.test(navigator.userAgent);
$.fn.inputDisabled = function() {
        var $this = $(this);
        var $parent = $this.parent();
        $parent.addClass('input-disabled');
        $parent.append('<div class="disabled-overlay" />');
        return $this;
}
 
if (is_firefox) {
        $('input:disabled, textarea:disabled').inputDisabled();
        $('.disabled-overlay').on('click', function(event) {
                event.preventDefault();
                var $this = $(this);
                var $input = $this.siblings('input');
                if (!$input.prop('disabled')) {
                        $input.focus();
                        $this.remove();
                }
        });
 
        $('.field').on('mouseover touchstart', function(e) {
                e.preventDefault();
                var $this = $(this);
                var $input = $this.children('input, textarea');
                if ($this.children('input:disabled').length != 0 && $this.children('.disabled-overlay').length == 0)
                        $input.inputDisabled();
        });
}
```

3) ...and this:
```css
.input-disabled {
 position: relative;
 .disabled-overlay {
  position: absolute;
  content: '';
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
 }
 input:not(:disabled) + .disabled-overlay {cursor: text;}
}
```

This works for me. For now, at least. Hopefully the author might work around the issue and this would really be a 'perfect' scrollbar.
