### ISSUE TITLE
Is there a show() method?

### ISSUE THREAD

**Issue by matthew-dean** [noraesae/perfect-scrollbar#405]
I'm having an issue where I'm programmatically setting the scrollTop position. If I run "update", it updates the position, I guess, but it doesn't show the scroller. Is there a way to force the scroller to show while programmatically incrementing the scroll position?

**Comment by DanielApt** [comment]
At this point there's no way to show the scrollbar, as the hiding / showing logic is done via css.

I'd suggest to add the following style-rules

```css
.show-scrollbar.ps-container > .ps-scrollbar-y-rail, 
.show-scrollbar.ps-container > .ps-scrollbar-x-rail {
   opacity: 0.6;
}
```

And then temporarily add the `show-scrollbar` class to the scroll container.
