### ISSUE TITLE
How to style when disabled?

### ISSUE THREAD

**Issue by loominade** [noraesae/perfect-scrollbar#485]
There are two states which may have a different style:

1. The regular style: When there is a scrollable scrollbar.
2. The `disabled` style: when there is enough space two show all the contents of the container, and the scrollbar cannot be used (disabled, greyed out)

How can I apply css on the second state?

**Comment by DanielApt** [comment]
In the 1st state, the combination of these classes will be on the container: `ps-container` and `ps-active-y` (or `ps-active-x`)

In the 2nd state, there will only be a `ps-container` 

To style it, I'd suggest doing:

```css
/* The 1st state */
.ps-container {
  opacity: .5;
}

/* the 2nd state */
.ps-container.ps-active-y {
  opacity: 1;
}
```
