### ISSUE TITLE
Right Paramter in custom theme is not used for setting styles in scrollbar-y

### ISSUE THREAD

**Issue by duichwer** [noraesae/perfect-scrollbar#496]
I created my own theme with scss an build it, but now i have got the problem, that my right paramter isn't used by the javascript to set the element style.

As you can see in this examlpe. I created my own theme and simply changed the right paramter to 1px.
```css
.ps-theme-mytheme > .ps-scrollbar-y-rail {  
    display: none;  
    position: absolute;  
    border-radius: 4px;  
    opacity: 0;  
    -webkit-transition: background-color .2s linear, opacity .2s linear;
    transition: background-color .2s linear, opacity .2s linear;
    right: 1px;
    width: 8px;
}
```
But later the scrollbar receives the elment-style with right: 3px.

You can check at this  [JSFiddle]( https://jsfiddle.net/LLru9kqt/)

I pretend that this might come from those styles, that become overridden by mytheme styles.
```css
ps-container > .ps-scrollbar-y-rail {
    display: none;
    position: absolute;
    border-radius: 4px;
    opacity: 0;
    -webkit-transition: background-color .2s linear, opacity .2s linear;
    transition: background-color .2s linear, opacity .2s linear;
    right: 3px;
    width: 8px;
}
```
