### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by snuuve** [noraesae/perfect-scrollbar#569]
Is it possible to make scrolling smooth (animated etc) ?

**Comment by noraesae** [comment]
Please add `transition` style like below:

```css
.ps-container > .ps-scrollbar-x-rail > .ps-scrollbar-x {
  transition: .2s linear left;
  /* maybe other vendor-prefixed transitions */
}
.ps-container > .ps-scrollbar-y-rail > .ps-scrollbar-y {
  transition: .2s linear top;
  /* maybe other vendor-prefixed transitions */
}
```

You can freely change the duration and timing function.
